site_name: SNVPhyl
site_url: http://snvphyl.readthedocs.org
site_description: SNVPhyl Whole Genome SNV Phylogenomics Pipeline.
repo_url: https://irida.corefacility.ca/gitlab/analysis-pipelines/snvphyl-galaxy
pages:
- [index.md, Home]
- [index.md, User, Overview]
- [user/usage.md, User, Usage]
- [user/output.md, User, Output]
- [install/index.md, Installation]
- [install/docker.md, Installation, Docker]
- [install/virtualmachine.md, Installation, Virtual Machine]
- [install/galaxy.md, Installation, Galaxy]
- [examples/index.md, Examples, Home]
- [examples/escherichia-coli.md, Examples, Escherichia coli]
- [examples/listeria-monocytogenes.md, Examples, Listeria monocytogenes]
- [examples/salmonella-enterica.md, Examples, Salmonella enterica]

theme: readthedocs
